[package]
name = "postui"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
toml = "0.8.20"
